<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>KrokMPOptimization2</AssemblyName>
    <RootNamespace>KrokMPOptimization2</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\..\wikiSearch\build\KrokMPOptimization2\bin\</OutputPath>
    <IntermediateOutputPath>$(MSBuildThisFileDirectory)..\..\..\wikiSearch\build\KrokMPOptimization2\obj\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\libs\BepInEx\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\libs\BepInEx\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="KrokoshaCasualtiesMP">
      <HintPath>..\..\libs\KrokMP\KrokoshaCasualtiesMP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LiteNetLib">
      <HintPath>..\..\libs\KrokMP\LiteNetLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>..\..\libs\KrokMP\Steamworks.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\libs\GameManaged\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\libs\GameManaged\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\libs\GameManaged\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\libs\GameManaged\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\libs\GameManaged\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\libs\GameManaged\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyPluginToPluginsRoot" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)KrokMPOptimization2.dll" DestinationFolder="$(MSBuildThisFileDirectory)" SkipUnchangedFiles="true" />
  </Target>
</Project>
